-- Publicar os planos 2026/27 como VIGENTES — atalho OPCIONAL (v52)
-- Rodar no SQL Editor do Supabase DEPOIS do sql/005 e do sql/006, e SÓ quando o
-- agrônomo tiver aprovado o plano. O caminho normal é a tela Escritório ›
-- Cadastros › Unidades e Plano (Rodar auditoria → Aprovado por → Publicar),
-- fazenda por fazenda; este arquivo faz o mesmo de uma vez.
--
-- Gerado por scripts/gerar_publicacao_plano.py a partir de
-- docs/plano/2026-27/auditoria_v1_resultado.json (auditoria rodada em 2026-09-03T21:58:30.732Z
-- sobre os mesmos dados do seed, com a função auditarPlano() do app).
-- Só publica versão em rascunho com auditoria ok; a vigente anterior vira "superado".
-- Pode ser rodado de novo: plano já vigente não muda.

begin;

-- Lagamar Café (Rodrigo) — auditoria OK
update public.plano_safra set auditoria_ok = true, auditoria_json = '{"ok": true, "quando": "2026-09-03T21:58:31.007Z", "versao_app": "v52", "itens": [{"titulo": "Toda unidade do plano existe, está ativa e é desta fazenda", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com calendário de adubação sem área (exceção: escrever \"sem área: ok\" em obs)", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Soma de kg por insumo bate com o resumo do deck (informa)", "bloqueante": false, "ok": false, "detalhes": ["ureia: calendários 40.000 kg × resumo do deck 48.000 kg (+8.000)", "KCl: calendários 105.000 kg × resumo do deck 109.000 kg (+4.000)"]}, {"titulo": "kg/ha por insumo dentro de ±50% da mediana da fazenda (informa)", "bloqueante": false, "ok": false, "detalhes": ["LAG-S01 Setor 01 — ureia 333 kg/ha (mediana 190)", "LAG-S02 Setor 02 — ureia 333 kg/ha (mediana 190)", "LAG-S03 Setor 03 — ureia 333 kg/ha (mediana 190)", "LAG-S01 Setor 01 — nitrato 1417 kg/ha (mediana 810)", "LAG-S02 Setor 02 — nitrato 1417 kg/ha (mediana 810)", "LAG-S03 Setor 03 — nitrato 1417 kg/ha (mediana 810)", "LAG-S01 Setor 01 — sulfato de amônio 646 kg/ha (mediana 357)", "LAG-S02 Setor 02 — sulfato de amônio 646 kg/ha (mediana 357)", "LAG-S03 Setor 03 — sulfato de amônio 646 kg/ha (mediana 357)", "LAG-S01 Setor 01 — KCl 1083 kg/ha (mediana 423)", "LAG-S02 Setor 02 — KCl 1083 kg/ha (mediana 423)", "LAG-S03 Setor 03 — KCl 1083 kg/ha (mediana 423)", "LAG-S04 Setor 04 — KCl 190 kg/ha (mediana 423)", "LAG-S06 Setor 06 — KCl 190 kg/ha (mediana 423)", "LAG-S01 Setor 01 — ácido bórico 48 kg/ha (mediana 29)", "LAG-S02 Setor 02 — ácido bórico 48 kg/ha (mediana 29)", "LAG-S03 Setor 03 — ácido bórico 48 kg/ha (mediana 29)", "LAG-S01 Setor 01 — sulfato de Zn 27 kg/ha (mediana 15)", "LAG-S02 Setor 02 — sulfato de Zn 27 kg/ha (mediana 15)", "LAG-S03 Setor 03 — sulfato de Zn 27 kg/ha (mediana 15)"]}, {"titulo": "Toda unidade com calendário tem calagem e vice-versa (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com status \"a confirmar\" (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Todo insumo-mês tem via (fertirrigação / lanço) definida (informa — na v1 nenhuma tem, é esperado)", "bloqueante": false, "ok": false, "detalhes": ["156 de 156 linhas sem via"]}]}'::jsonb
  where fazenda_app = 'Lagamar Café (Rodrigo)' and safra = '2026/27' and versao = 1 and status = 'rascunho';
update public.plano_safra set status = 'superado' where fazenda_app = 'Lagamar Café (Rodrigo)' and safra = '2026/27' and status = 'vigente' and versao <> 1;
update public.plano_safra set status = 'vigente', vigente_de = current_date, aprovado_por = coalesce(aprovado_por, 'Salvino'), aprovado_em = coalesce(aprovado_em, now())
  where fazenda_app = 'Lagamar Café (Rodrigo)' and safra = '2026/27' and versao = 1 and status = 'rascunho' and auditoria_ok;

-- Mata Preta — Café — auditoria OK
update public.plano_safra set auditoria_ok = true, auditoria_json = '{"ok": true, "quando": "2026-09-03T21:58:31.149Z", "versao_app": "v52", "itens": [{"titulo": "Toda unidade do plano existe, está ativa e é desta fazenda", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com calendário de adubação sem área (exceção: escrever \"sem área: ok\" em obs)", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Soma de kg por insumo bate com o resumo do deck (informa)", "bloqueante": false, "ok": false, "detalhes": ["ureia: calendários 31.000 kg × resumo do deck 30.500 kg (-500)"]}, {"titulo": "kg/ha por insumo dentro de ±50% da mediana da fazenda (informa)", "bloqueante": false, "ok": false, "detalhes": ["MTP-S01 Setor 01 — Phusion 0 kg/ha (mediana 150)", "MTP-S02 Setor 02 — Phusion 0 kg/ha (mediana 150)"]}, {"titulo": "Toda unidade com calendário tem calagem e vice-versa (informa)", "bloqueante": false, "ok": false, "detalhes": ["MTP-3PT 3º plantio (torres): calendário sem calagem", "MTP-P26 Plantio 2026: calagem sem calendário"]}, {"titulo": "Nenhuma unidade com status \"a confirmar\" (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Todo insumo-mês tem via (fertirrigação / lanço) definida (informa — na v1 nenhuma tem, é esperado)", "bloqueante": false, "ok": false, "detalhes": ["141 de 141 linhas sem via"]}]}'::jsonb
  where fazenda_app = 'Mata Preta — Café' and safra = '2026/27' and versao = 1 and status = 'rascunho';
update public.plano_safra set status = 'superado' where fazenda_app = 'Mata Preta — Café' and safra = '2026/27' and status = 'vigente' and versao <> 1;
update public.plano_safra set status = 'vigente', vigente_de = current_date, aprovado_por = coalesce(aprovado_por, 'Salvino'), aprovado_em = coalesce(aprovado_em, now())
  where fazenda_app = 'Mata Preta — Café' and safra = '2026/27' and versao = 1 and status = 'rascunho' and auditoria_ok;

-- Monte Carmelo — Café — auditoria OK
update public.plano_safra set auditoria_ok = true, auditoria_json = '{"ok": true, "quando": "2026-09-03T21:58:31.270Z", "versao_app": "v52", "itens": [{"titulo": "Toda unidade do plano existe, está ativa e é desta fazenda", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com calendário de adubação sem área (exceção: escrever \"sem área: ok\" em obs)", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Soma de kg por insumo bate com o resumo do deck (informa)", "bloqueante": false, "ok": false, "detalhes": ["ureia: calendários 61.500 kg × resumo do deck 65.500 kg (+4.000)", "nitrato: calendários 251.000 kg × resumo do deck 268.000 kg (+17.000)", "sulfato de amônio: calendários 115.000 kg × resumo do deck 122.500 kg (+7.500)", "KCl: calendários 211.000 kg × resumo do deck 215.000 kg (+4.000)", "Phusion: calendários 32.500 kg × resumo do deck 24.500 kg (-8.000)", "sulfato de Mn: calendários 4.050 kg × resumo do deck 4.300 kg (+250)", "ácido bórico: calendários 8.600 kg × resumo do deck 9.150 kg (+550)", "sulfato de Zn: calendários 4.825 kg × resumo do deck 5.150 kg (+325)"]}, {"titulo": "kg/ha por insumo dentro de ±50% da mediana da fazenda (informa)", "bloqueante": false, "ok": false, "detalhes": ["MCC-ERA Sr. Ernani alto — ureia 340 kg/ha (mediana 200)", "MCC-ERA Sr. Ernani alto — nitrato 1400 kg/ha (mediana 800)", "MCC-ERA Sr. Ernani alto — sulfato de amônio 630 kg/ha (mediana 367)", "MCC-CXP Caxico represa — KCl 1407 kg/ha (mediana 720)", "MCC-S04 M. Carmelo st04 — KCl 333 kg/ha (mediana 720)", "MCC-ERA Sr. Ernani alto — sulfato de Mn 22 kg/ha (mediana 13)", "MCC-ERA Sr. Ernani alto — ácido bórico 48 kg/ha (mediana 27)", "MCC-ERA Sr. Ernani alto — sulfato de Zn 27 kg/ha (mediana 15)"]}, {"titulo": "Toda unidade com calendário tem calagem e vice-versa (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com status \"a confirmar\" (informa)", "bloqueante": false, "ok": false, "detalhes": ["MCC-CXR Caxico M Novo recepa"]}, {"titulo": "Todo insumo-mês tem via (fertirrigação / lanço) definida (informa — na v1 nenhuma tem, é esperado)", "bloqueante": false, "ok": false, "detalhes": ["300 de 300 linhas sem via"]}]}'::jsonb
  where fazenda_app = 'Monte Carmelo — Café' and safra = '2026/27' and versao = 1 and status = 'rascunho';
update public.plano_safra set status = 'superado' where fazenda_app = 'Monte Carmelo — Café' and safra = '2026/27' and status = 'vigente' and versao <> 1;
update public.plano_safra set status = 'vigente', vigente_de = current_date, aprovado_por = coalesce(aprovado_por, 'Salvino'), aprovado_em = coalesce(aprovado_em, now())
  where fazenda_app = 'Monte Carmelo — Café' and safra = '2026/27' and versao = 1 and status = 'rascunho' and auditoria_ok;

-- Rio Preto-Lagamar — Café — auditoria OK
update public.plano_safra set auditoria_ok = true, auditoria_json = '{"ok": true, "quando": "2026-09-03T21:58:31.379Z", "versao_app": "v52", "itens": [{"titulo": "Toda unidade do plano existe, está ativa e é desta fazenda", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com calendário de adubação sem área (exceção: escrever \"sem área: ok\" em obs)", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Soma de kg por insumo bate com o resumo do deck (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "kg/ha por insumo dentro de ±50% da mediana da fazenda (informa)", "bloqueante": false, "ok": false, "detalhes": ["RPL-1P-S01 Setor 01 — KCl 1125 kg/ha (mediana 585)", "RPL-1P-S02 Setor 02 — KCl 1125 kg/ha (mediana 585)", "RPL-1P-S03 Setor 03 — KCl 1125 kg/ha (mediana 585)", "RPL-1P-S04 Setor 04 — KCl 938 kg/ha (mediana 585)", "RPL-1P-S05 Setor 05 — KCl 938 kg/ha (mediana 585)", "RPL-1P-S06 Setor 06 — KCl 1263 kg/ha (mediana 585)", "RPL-2P-S01 2º plantio st01 — KCl 233 kg/ha (mediana 585)", "RPL-2P-S02 2º plantio st02 — KCl 233 kg/ha (mediana 585)", "RPL-2P-S03 2º plantio st03 — KCl 233 kg/ha (mediana 585)", "RPL-2P-S04 2º plantio st04 — KCl 233 kg/ha (mediana 585)", "RPL-2P-S05 2º plantio st05 — KCl 233 kg/ha (mediana 585)", "RPL-2P-S06 2º plantio st06 — KCl 233 kg/ha (mediana 585)"]}, {"titulo": "Toda unidade com calendário tem calagem e vice-versa (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com status \"a confirmar\" (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Todo insumo-mês tem via (fertirrigação / lanço) definida (informa — na v1 nenhuma tem, é esperado)", "bloqueante": false, "ok": false, "detalhes": ["276 de 276 linhas sem via"]}]}'::jsonb
  where fazenda_app = 'Rio Preto-Lagamar — Café' and safra = '2026/27' and versao = 1 and status = 'rascunho';
update public.plano_safra set status = 'superado' where fazenda_app = 'Rio Preto-Lagamar — Café' and safra = '2026/27' and status = 'vigente' and versao <> 1;
update public.plano_safra set status = 'vigente', vigente_de = current_date, aprovado_por = coalesce(aprovado_por, 'Salvino'), aprovado_em = coalesce(aprovado_em, now())
  where fazenda_app = 'Rio Preto-Lagamar — Café' and safra = '2026/27' and versao = 1 and status = 'rascunho' and auditoria_ok;

-- Vereda Café 5º e 6º — auditoria OK
update public.plano_safra set auditoria_ok = true, auditoria_json = '{"ok": true, "quando": "2026-09-03T21:58:31.561Z", "versao_app": "v52", "itens": [{"titulo": "Toda unidade do plano existe, está ativa e é desta fazenda", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com calendário de adubação sem área (exceção: escrever \"sem área: ok\" em obs)", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Soma de kg por insumo bate com o resumo do deck (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "kg/ha por insumo dentro de ±50% da mediana da fazenda (informa)", "bloqueante": false, "ok": false, "detalhes": ["V56-6MN 6º M Novo — KCl 250 kg/ha (mediana 733)"]}, {"titulo": "Toda unidade com calendário tem calagem e vice-versa (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com status \"a confirmar\" (informa)", "bloqueante": false, "ok": false, "detalhes": ["V56-6MN 6º M Novo"]}, {"titulo": "Todo insumo-mês tem via (fertirrigação / lanço) definida (informa — na v1 nenhuma tem, é esperado)", "bloqueante": false, "ok": false, "detalhes": ["115 de 115 linhas sem via"]}]}'::jsonb
  where fazenda_app = 'Vereda Café 5º e 6º' and safra = '2026/27' and versao = 1 and status = 'rascunho';
update public.plano_safra set status = 'superado' where fazenda_app = 'Vereda Café 5º e 6º' and safra = '2026/27' and status = 'vigente' and versao <> 1;
update public.plano_safra set status = 'vigente', vigente_de = current_date, aprovado_por = coalesce(aprovado_por, 'Salvino'), aprovado_em = coalesce(aprovado_em, now())
  where fazenda_app = 'Vereda Café 5º e 6º' and safra = '2026/27' and versao = 1 and status = 'rascunho' and auditoria_ok;

-- Vereda Romaria — auditoria OK
update public.plano_safra set auditoria_ok = true, auditoria_json = '{"ok": true, "quando": "2026-09-03T21:58:31.682Z", "versao_app": "v52", "itens": [{"titulo": "Toda unidade do plano existe, está ativa e é desta fazenda", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com calendário de adubação sem área (exceção: escrever \"sem área: ok\" em obs)", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Soma de kg por insumo bate com o resumo do deck (informa)", "bloqueante": false, "ok": false, "detalhes": ["ureia: calendários 34.500 kg × resumo do deck 34.000 kg (-500)", "KCl: calendários 177.000 kg × resumo do deck 183.000 kg (+6.000)"]}, {"titulo": "kg/ha por insumo dentro de ±50% da mediana da fazenda (informa)", "bloqueante": false, "ok": false, "detalhes": ["ROM-S01 Romaria 01 — ureia 393 kg/ha (mediana 200)", "ROM-S01 Romaria 01 — nitrato 1571 kg/ha (mediana 800)", "ROM-S01 Romaria 01 — sulfato de amônio 714 kg/ha (mediana 355)", "ROM-S01 Romaria 01 — KCl 2000 kg/ha (mediana 1025)", "ROM-S01 Romaria 01 — sulfato de Mn 25 kg/ha (mediana 13)", "ROM-S01 Romaria 01 — ácido bórico 57 kg/ha (mediana 30)", "ROM-S01 Romaria 01 — sulfato de Zn 32 kg/ha (mediana 15)"]}, {"titulo": "Toda unidade com calendário tem calagem e vice-versa (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com status \"a confirmar\" (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Todo insumo-mês tem via (fertirrigação / lanço) definida (informa — na v1 nenhuma tem, é esperado)", "bloqueante": false, "ok": false, "detalhes": ["185 de 185 linhas sem via"]}]}'::jsonb
  where fazenda_app = 'Vereda Romaria' and safra = '2026/27' and versao = 1 and status = 'rascunho';
update public.plano_safra set status = 'superado' where fazenda_app = 'Vereda Romaria' and safra = '2026/27' and status = 'vigente' and versao <> 1;
update public.plano_safra set status = 'vigente', vigente_de = current_date, aprovado_por = coalesce(aprovado_por, 'Salvino'), aprovado_em = coalesce(aprovado_em, now())
  where fazenda_app = 'Vereda Romaria' and safra = '2026/27' and versao = 1 and status = 'rascunho' and auditoria_ok;

-- Vereda — Café — auditoria OK
update public.plano_safra set auditoria_ok = true, auditoria_json = '{"ok": true, "quando": "2026-09-03T21:58:31.791Z", "versao_app": "v52", "itens": [{"titulo": "Toda unidade do plano existe, está ativa e é desta fazenda", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com calendário de adubação sem área (exceção: escrever \"sem área: ok\" em obs)", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Soma de kg por insumo bate com o resumo do deck (informa)", "bloqueante": false, "ok": false, "detalhes": ["ureia: calendários 71.000 kg × resumo do deck 73.000 kg (+2.000)", "nitrato: calendários 306.000 kg × resumo do deck 304.000 kg (-2.000)", "sulfato de amônio: calendários 163.500 kg × resumo do deck 139.000 kg (-24.500)", "KCl: calendários 369.000 kg × resumo do deck 387.000 kg (+18.000)", "ácido bórico: calendários 10.625 kg × resumo do deck 10.600 kg (-25)", "sulfato de Zn: calendários 6.125 kg × resumo do deck 5.950 kg (-175)"]}, {"titulo": "kg/ha por insumo dentro de ±50% da mediana da fazenda (informa)", "bloqueante": false, "ok": false, "detalhes": ["VEC-S09 Setor 9 — ureia 0 kg/ha (mediana 189)", "VEC-S08 Setor 08 — sulfato de amônio 712 kg/ha (mediana 375)", "VEC-S09 Setor 9 — sulfato de amônio 571 kg/ha (mediana 375)", "VEC-S01 Setor 01 — KCl 438 kg/ha (mediana 949)", "VEC-S07 Setor 07 — KCl 0 kg/ha (mediana 949)"]}, {"titulo": "Toda unidade com calendário tem calagem e vice-versa (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com status \"a confirmar\" (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Todo insumo-mês tem via (fertirrigação / lanço) definida (informa — na v1 nenhuma tem, é esperado)", "bloqueante": false, "ok": false, "detalhes": ["243 de 243 linhas sem via"]}]}'::jsonb
  where fazenda_app = 'Vereda — Café' and safra = '2026/27' and versao = 1 and status = 'rascunho';
update public.plano_safra set status = 'superado' where fazenda_app = 'Vereda — Café' and safra = '2026/27' and status = 'vigente' and versao <> 1;
update public.plano_safra set status = 'vigente', vigente_de = current_date, aprovado_por = coalesce(aprovado_por, 'Salvino'), aprovado_em = coalesce(aprovado_em, now())
  where fazenda_app = 'Vereda — Café' and safra = '2026/27' and versao = 1 and status = 'rascunho' and auditoria_ok;

-- Água Limpa — auditoria OK
update public.plano_safra set auditoria_ok = true, auditoria_json = '{"ok": true, "quando": "2026-09-03T21:58:31.896Z", "versao_app": "v52", "itens": [{"titulo": "Toda unidade do plano existe, está ativa e é desta fazenda", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com calendário de adubação sem área (exceção: escrever \"sem área: ok\" em obs)", "bloqueante": true, "ok": true, "detalhes": []}, {"titulo": "Soma de kg por insumo bate com o resumo do deck (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "kg/ha por insumo dentro de ±50% da mediana da fazenda (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Toda unidade com calendário tem calagem e vice-versa (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Nenhuma unidade com status \"a confirmar\" (informa)", "bloqueante": false, "ok": true, "detalhes": []}, {"titulo": "Todo insumo-mês tem via (fertirrigação / lanço) definida (informa — na v1 nenhuma tem, é esperado)", "bloqueante": false, "ok": false, "detalhes": ["117 de 117 linhas sem via"]}]}'::jsonb
  where fazenda_app = 'Água Limpa' and safra = '2026/27' and versao = 1 and status = 'rascunho';
update public.plano_safra set status = 'superado' where fazenda_app = 'Água Limpa' and safra = '2026/27' and status = 'vigente' and versao <> 1;
update public.plano_safra set status = 'vigente', vigente_de = current_date, aprovado_por = coalesce(aprovado_por, 'Salvino'), aprovado_em = coalesce(aprovado_em, now())
  where fazenda_app = 'Água Limpa' and safra = '2026/27' and versao = 1 and status = 'rascunho' and auditoria_ok;

-- conferência: uma vigente por fazenda
do $$
declare n integer;
begin
  select count(*) into n from public.plano_safra where safra = '2026/27' and status = 'vigente';
  raise notice 'planos vigentes na safra 2026/27: %', n;
end $$;

commit;
